--- 
- 
  become: true
  become_user: root
  hosts: localhost
  name: "zips files older than 10 days"
  tasks: 
    - name: "Zip /var/log"
      shell: "find /var/log/ -type f -name  '\"*log*\"'  -atime +10 -exec gzip {} \\;"
