--- 
- 
  become: true
  become_user: root
  hosts: localhost
  name: "zips files older than 90 days"
  tasks: 
    - 
      name: "Zip /var/log"
      shell: "find /var/log/ -type f -name  '\"*log*\"'  -mtime +0 -exec gzip -9 {} \\;"
