---
- hosts: kernel
  become: yes
  become_method: sudo
  tasks: 
    - name: Update kernel to latest
      when: ansible_distribution == "CentOS" and ansible_distribution_version == "7"
      package:
        name: kernel
        state: latest
    - name: Restart the system
      when: ansible_distribution == "CentOS" and ansible_distribution_version == "7"
      reboot:
      