--- # add or remove record from route 53 
- name: Create a record on route 53 with user input
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - route53:
        state: "{{state}}" #present will create and absent will remove
        zone: "{{zone}}" #The DNS zone to modify - domain name
        record: "{{record}}" # The full DNS record to create or delete
        type: "{{type}}" #The type of DNS record to create
        ttl: "{{ttl}}" #The TTL to give the new record
        value: "{{value}}" #The new value when creating a DNS record. Ip address 
        wait: "{{wait}}" # Wait until the changes have been replicated to all Amazon Route 53 DNS servers. Yes or No