---
- name: Helps to download file
  hosts: alll
  become: yes
  become_method: sudo
  vars_prompt:
    - name: URL
      promt: "Give me the url:"
      private: no
  tasks:
    - name: Download 1 package
      get_url:
        url: ""
        dest: /tmp/