---
- name: Create ec2 instance 
  hosts: localhost
  tasks: 
    - name: Create instances
      ec2:
        key_name: myMacKey
        instance_type: t2.micro
        image: ami-04768381bf606e2b3
        count: 3
        