---
- name: Installs ncpa agent on instances
  hosts: all
  become: yes
  become_user: root 
  tasks: 
    - block:
      - name: Create Repo on Centos6
        shell: "rpm -Uvh http://repo.nagios.com/nagios/6/nagios-repo-6-3.el6.noarch.rpm"
    
      - name: Install ncpa on centos 6
        package:
          name: ncpa
          state: present
        notify: NCPA_CENTOS_6
      - name: Change the code inside ncpa.cfg 
        lineinfile:
          path: /usr/local/ncpa/etc/ncpa.cfg
          regexp: "community_string = mytoken"
          line: "community_string = STRONGPASSWORD"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
    
    - block:
      - name: Create repo on centos 7 
        shell: "rpm -Uvh http://repo.nagios.com/nagios/7/nagios-repo-7-3.el7.noarch.rpm"

      - name: Install ncpa on centos 7
        package:
          name: ncpa
          state: present
        notify: NCPA_CENTOS_7

      - name: Change the code inside ncpa.cfg
        lineinfile:
          path: /usr/local/ncpa/etc/ncpa.cfg
          regexp: "community_string = mytoken"
          line: "community_string = STRONGPASSWORD"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 

    - block:
      - name: Create repo on Amazon
        shell: "rpm -Uvh http://repo.nagios.com/nagios/7/nagios-repo-7-3.el7.noarch.rpm"

      - name: Install ncpa on centos 7
        package:
          name: ncpa
          state: present
        notify: NCPA_AMAZON

      - name: Change the code inside ncpa.cfg
        lineinfile:
          path: /usr/local/ncpa/etc/ncpa.cfg
          regexp: "community_string = mytoken"
          line: "community_string = STRONGPASSWORD"
      when: ansible_distribution == "Amazon"


  handlers:
    - name: NCPA_CENTOS_6
      service:
        name: ncpa_listener
        state: restarted

    - name: NCPA_CENTOS_7
      systemd:
        name: ncpa_listener
        state: restarted

    - name: NCPA_AMAZON
      systemd:
        name: ncpa_listener
        state: restarted