---
- name: install r1soft agent
  hosts: target
  become: yes
  become_method: sudo
  tasks:
    # This line for CentOS 7
    - block:
      - name: Creating Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent
          state: latest
        notify: R1SOFT_INSTALLED_ON_CENTOS_7
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  
    # this line for CentOS 6
    - block:
      - name: Creating Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent
          state: latest
        notify: R1SOFT_INSTALLED_ON_CENTOS_6
      - name: Start agent
        service:
          name: cdp-agent
          state: restarted

      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

    # this line for CentOS 8
    - block:
      - name: Creating Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent
          state: latest
        notify: R1SOFT_INSTALLED_ON_CENTOS_8
      - name: Start agent
        systemd:
          name: sbm-agent
          state: restarted

      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
    
    # this line for Fedora
    - block:
      - name: Creating Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent
          state: latest
      - name: Start agent
        systemd:
          name: sbm-agent
          state: restarted

      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "Fedora" and ansible_distribution_major_version == "28"
    
    handlers:
      - name: R1SOFT_INSTALLED_ON_CENTOS_7
        systemd:
          name: sbm-agent
          state: restarted 
      - name: R1SOFT_INSTALLED_ON_CENTOS_6
        service:
          name: cdp-agent
          state: restarted 
      - name: R1SOFT_INSTALLED_ON_CENTOS_8
        systemd:
          name: sbm-agent
          state: restarted 