---
- name: Adds user with ssh key 
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Add 1 user
      user:
       name: "{{user}}"
       state: present
    
    - name: Create a 
    - name: add public key
      lineinfile:
        path: "/home/{{user}}/.ssh/authorized_keys"
        line: "{{line}}"
      
      
