- block:
  - name: Create Repository
    copy: 
      src: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo

  - name: Install r1soft pgent
    package: 
      name: serverbackup-enterprise-agent 
      state: present

  
  - name: Get key
    shell: "r1soft-setup --get-key http://18.220.36.80"
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

   


