---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Gathering the facts...
      ec2_remote_facts:
        region: us-east-1
        filters:
          "tag:Name": QA
          "tag:Name": Prod
          "tag:Name": Dev
      register: ec2_facts

    - name: Snapshoting the instance...
      ec2_snapshot:
        region: us-east-1
        volume_id: "{{ item.volume_id }}"
      ec2_snapshot_copy:
        source_region: us-east-1
        region: us-east-2
        source_snapshot_id: "{{item.SnapshotId}}"
        wait: yes
        wait_timeout: 1200   # Default timeout is 600
      register: snapshot_id
      with_items: "{{ ec2_facts | json_query('instances[].block_device_mapping[]'| jq '.Snapshots[] | select(.StartTime < "'$(date --date='-1 month' '+%Y-%m-%d')'") | [.Description, .StartTime, .SnapshotId]') }}"
      - 
  
  
      
      
