---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Find snapshots.
      ec2_snapshot_facts:
        region: us-east-1
      register: ec2_facts
    - ec2_snapshot_copy:
        source_region: us-east-1
        region: us-east-2
        source_snapshot_id: "{{item}}"  #"{{item.snapshot_id}}"
        description: "disaster  recovery"
        tags: '{"Name":"Prod","Name":"Dev","Name":"QA"}'
      
      with_items: 
        - snap-012c2d75275874120
        - snap-0416a2cb800a35978
        - snap-091768dbb8c8e7512
  
  
      
