---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Find snapshots.
      ec2_snapshot_facts:
        region: us-east-1
      register: ec2_facts
    - ec2_snapshot_copy:
        source_region: us-east-1
        region: us-east-2
        source_snapshot_id: "{{item.snapshot_id}}"
        wait: yes
        wait_timeout: 1200   # Default timeout is 600
      with_items: "{{ ec2_facts )}}"
  
  
      
