---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    
    - name: Find snapshots of prod
      ec2_snapshot_facts:
        region: "us-east-1"
        filters:
          status: completed
          "tag:Name": Prod
      register: ec2_facts_prod
    
    - name: Find snapshots of qa
      ec2_snapshot_facts:
        region: "us-east-1"
        filters:
          status: completed
          "tag:Name": QA
      register: ec2_facts_qa
      
    - name: Find snapshots of dev
      ec2_snapshot_facts:
        region: "us-east-1"
        filters:
          status: completed
          "tag:Name": Dev
      register: ec2_facts_dev
    - debug:
        msg:"{{ec2_facts_prod.snapshots[].snapshot_id(0)}}"
    
        
    - name: Snapshot copy to another region
      ec2_snapshot_copy:
        source_region: us-east-1
        region: us-east-2
        description: "disaster  recovery"
        source_snapshot_id: "{{item.snapid)}}"
        tags: "{{item.tag}}"
      with_items:
        - { snapid: '{{ec2_facts_prod.snapshots[].snapshot_id(0)}}', tag: '{"Name":"Prod"}' }
        - { snapid: '{{ec2_facts_qa.snapshots[].snapshot_id(0)}}', tag: '{"Name":"QA"}' }
        - { snapid: '{{ec2_facts_dev.snapshots[].snapshot_id(0)}}', tag: '{"Name":"Dev"}' }
        
        
       
        
      

