---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Find snapshots.
      ec2_remote_facts:
        region: us-east-1
        filters:
          "tag:Name": [QA,Prod,Dev]
      register: ec2_facts
      
      ec2_snapshot_facts:
        region: us-east-1
        filters:
          status: completed
      register: ec2_facts1
      
      ec2_snapshot_facts:
        region: us-east-1
        
         
      register: ec2_facts2
      
      ec2_snapshot_facts:
        region: us-east-1
        filters:
          "tag:Name": "QA"
      register: ec2_facts3
      
    - debug: var=ec2_facts.stdout_lines
    - debug: var=ec2_facts1.stdout_lines
    - debug: var=ec2_facts2.stdout_lines
    - debug: var=ec2_facts3.stdout_lines
      
   # - ec2_snapshot_copy:
   #    source_region: us-east-1
   #   region: us-east-2
   #    source_snapshot_id: "{{item.snap_id}}"  #"{{item.snapshot_id}}"
   #     description: "disaster  recovery"
   #     tags: "{{item.tag}}"
      
   #   with_items: 
   #     - { snap_id: 'ec2_facts1 | json_query('snapshot[].snapshot_id')', tag: '{"Name":"Prod"}' }
   #     - { snap_id: 'ec2_facts2 | json_query('snapshot[].snapshot_id')', tag: '{"Name":"Dev"}' }
   #      - { snap_id: 'ec2_facts3 | json_query('snapshot[].snapshot_id')', tag: '{"Name":"QA"}' }
        
        
        
       

