---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Find snapshots.
      ec2_snapshot_facts:
        region: us-east-1
      register: ec2_facts
    - ec2_snapshot_copy:
        source_region: us-east-1
        region: us-east-2
        source_snapshot_id: "{{item.snap_id}}"  #"{{item.snapshot_id}}"
        description: "disaster  recovery"
        tags: "{{item.tag}}"
      
      with_items: 
        - { snap_id: 'snap-012c2d75275874120', tag: '{"Name":"Prod"}' }
        - { snap_id: 'snap-0416a2cb800a35978', tag: '{"Name":"Dev"}' }
        - { snap_id: 'snap-091768dbb8c8e7512', tag: '{"Name":"QA"}' }
     
  
  
      
