---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    
    - name: Find snapshots.
      ec2_snapshot_facts:
        region: "us-east-1"
        filters:
          status: completed
          "tag:Name": ["Prod","QA","Dev"]
      register: ec2_facts
    - debug:
        msg: "{{ ec2_facts }}"
    
       

