---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Copying snapshot to different region
      ec2_snapshot_copy:
        source_region: us-east-1
        region: us-east-2
        source_snapshot_id: "{{item.SnapshotId}}"
        wait: yes
        wait_timeout: 1200   # Default timeout is 600
      register: snapshot_id
      with_items: "{{ $ aws ec2 describe-snapshots --owner self | jq '.Snapshots[] | select(.StartTime < "'$(date --date='-1 month' '+%Y-%m-%d')'") | [.Description, .StartTime, .SnapshotId]') }}"
      
      
