---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Find snapshots.
      ec2_snapshot_facts:
        region: us-east-1
        filters:
        "tag:Name": [QA,Prod,Dev]
      register: ec2_snapshot_facts

    - name: Print snapshot facts
      debug:
        msg: "{{ snapshot_ids }}"

   
  
  
      
