---
- name: Create a snapshot on existing volume
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: create a snapshot on exisitng volume
      local_action:
        module: ec2_snapshot
        instance_id: i-0096eb112fd43bd0d
        device_name: /dev/sda1                            #volume ID of CentOS7 Machine.
        region: us-east-1                                #name of region where my volume is located.
        description: snapshot of dev instance 
        snapshot_tags:
          frequency: daily
          source: /data # giving description or naming convention for my snapshot
        
        
